#%RAML 1.0
title: Task Manager API
version: 1.0
baseUri: http://localhost:8081

/task:
  get:
    queryParameters:
      id:
    responses:
      200:
        body:
          application/json:
            example: |
              { "ID": 86849091, "Task name": "Pass in Exams", "Description": "Keep studying", "Target date": "23-01-2017" }
  post:
    queryParameters: 
      taskname:
      description:
      target:
    responses:
      201:
        body:
          application/json:
            example: |
              {"message": "Task Registered!!!"}
  
  put:
    queryParameters: 
      taskname:
      description:
      target:
    responses:
      200:
        body: 
          application/json: 
            example: |
              {"message": "Task Updated!!!"}

  
  delete:
    queryParameters: 
      id:
    responses:
      204:
        body: 
          application/json: 
            example: |
              {"message": "Task Deleted!!!"}