CREATE TABLE IF NOT EXISTS TO_DOS (
	id INT AUTO_INCREMENT PRIMARY KEY,
	NAME_TASK VARCHAR NOT NULL,
	TASK_DESC VARCHAR NOT NULL,
	EXPECTED_DATE VARCHAR NOT NULL
);


INSERT INTO TO_DOS (NAME_TASK, TASK_DESC, EXPECTED_DATE) VALUES ('Estudar', 'Treinar um pouco de MULE', '31-MAR-17');
INSERT INTO TO_DOS (NAME_TASK, TASK_DESC, EXPECTED_DATE) VALUES ('MEL', 'Estudar Mule Expression Language', '31-MAR-17');
